<?php 
require_once('/src/head.php'); 
require_once('/src/header.php');
require_once('/src/sidebar.php');  
require_once('/src/breadcum.php'); 
require_once('/src/content.php'); 
require_once('/src/footer.php'); 
require_once('/src/scripts.php'); 
?>